name: Deploy Gatsby to GitHub Pages

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # 使用 Node.js 18.x
        cache: 'yarn'      # 缓存 Yarn 依赖

    # 安装依赖
    - name: Install dependencies
      run: yarn install

    # 构建 Gatsby 网站
    - name: Build Gatsby site
      run: yarn build

    # 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的内置令牌
        publish_dir: ./public # Gatsby 构建输出的目录
