name: Deploy Gatsby to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: 安装依赖
    - name: Install dependencies
      run: npm install

    # Step 4: 构建 Gatsby 网站
    - name: Build Gatsby site
      run: npm run build

    # Step 5: 部署到 GitHub Pages（使用 GitHub Token）
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Secrets 中的 Token
        publish_dir: ./public  # Gatsby 构建的输出目录
        publish_branch: gh-pages  # 推送到 gh-pages 分支
